export class ServersDB {
  public servers = [
    {
      '_id': 1,
      'name': 'Development',
      'host': 'winmaxd01.one.loc',
      'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxd01.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB',      
      'isActive': true      
    },
    {
      '_id': 2,
      'name': 'Test',
      'host': 'winmaxt01.one.loc',
      //'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxt01.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB', 
      'isActive': true      
    },
    {
      '_id': 3,
      'name': 'TRAIN 01',
      'host': 'winmaxtr01.one.loc',
      //'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxtr01.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB', 
      'isActive': true      
    },
    {
      '_id': 4,
      'name': 'TRAIN 02',
      'host': 'winmaxtr02.one.loc',
      //'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxtr01.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB', 
      'isActive': true      
    },
    {
      '_id': 5,
      'name': 'UAT 01',
      'host': 'winmaxuat01.one.loc',
      //'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxuat01.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB', 
      'isActive': true      
    },
    {
      '_id': 6,
      'name': 'UAT 02',
      'host': 'winmaxuat01.one.loc',
      //'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxuat01.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB', 
      'isActive': true      
    },
    {
      '_id': 7,
      'name': 'Production 01',
      'host': 'winmaxp01.one.loc',
      //'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxuat01.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB', 
      'isActive': true      
    },
    {
      '_id': 8,
      'name': 'Production 02',
      'host': 'winmaxp02.one.loc',
      //'hostApp': 'MAXIMO',
      'hostAppServer': 'WebSphere',
      'appServerPort': '9043',
      'isAppServerSecure': true,
      'appServerURL': 'https://winmaxp02.one.loc:9043/ibm/console',
      'os': 'Windows',
      'ip': '0.0.0.0',
      'isVM': true,
      'core': '4',
      'ram': '4 GB',
      'hdd': '100 GB', 
      'isActive': true      
    }   
  ]
}    